INSERT INTO countries(country_id, display_name) VALUES("afg","afghanistan");
INSERT INTO countries(country_id, display_name) VALUES("alb","albania");
INSERT INTO countries(country_id, display_name) VALUES("arg","argentina");
INSERT INTO countries(country_id, display_name) VALUES("aus","australia");
INSERT INTO countries(country_id, display_name) VALUES("aut","austria");
INSERT INTO countries(country_id, display_name) VALUES("bel","belgium");
INSERT INTO countries(country_id, display_name) VALUES("bgr","bulgaria");
INSERT INTO countries(country_id, display_name) VALUES("bmu","bermuda");
INSERT INTO countries(country_id, display_name) VALUES("bol","bolivia");
INSERT INTO countries(country_id, display_name) VALUES("bra","brazil");
INSERT INTO countries(country_id, display_name) VALUES("can","canada");
INSERT INTO countries(country_id, display_name) VALUES("che","switzerland");
INSERT INTO countries(country_id, display_name) VALUES("chl","chile");
INSERT INTO countries(country_id, display_name) VALUES("chn","china");
INSERT INTO countries(country_id, display_name) VALUES("col","colombia");
INSERT INTO countries(country_id, display_name) VALUES("com","comoros");
INSERT INTO countries(country_id, display_name) VALUES("cri","costa rica");
INSERT INTO countries(country_id, display_name) VALUES("csk","czechoslovakia");
INSERT INTO countries(country_id, display_name) VALUES("cub","cuba");
INSERT INTO countries(country_id, display_name) VALUES("cuw","curacao");
INSERT INTO countries(country_id, display_name) VALUES("cyp","Cyprus");
INSERT INTO countries(country_id, display_name) VALUES("deu","germany");
INSERT INTO countries(country_id, display_name) VALUES("dnk","denmark");
INSERT INTO countries(country_id, display_name) VALUES("ecu","ecuador");
INSERT INTO countries(country_id, display_name) VALUES("egy","egypt");
INSERT INTO countries(country_id, display_name) VALUES("eri","eritrea");
INSERT INTO countries(country_id, display_name) VALUES("esp","spain");
INSERT INTO countries(country_id, display_name) VALUES("est","estonia");
INSERT INTO countries(country_id, display_name) VALUES("eth","ethiopia");
INSERT INTO countries(country_id, display_name) VALUES("fin","finland");
INSERT INTO countries(country_id, display_name) VALUES("fji","fiji");
INSERT INTO countries(country_id, display_name) VALUES("fra","france");
INSERT INTO countries(country_id, display_name) VALUES("gbr","great britain");
INSERT INTO countries(country_id, display_name) VALUES("grc","greece");
INSERT INTO countries(country_id, display_name) VALUES("gtm","guatemala");
INSERT INTO countries(country_id, display_name) VALUES("haw","hawaii");
INSERT INTO countries(country_id, display_name) VALUES("hkg","hong kong");
INSERT INTO countries(country_id, display_name) VALUES("hnd","honduras");
INSERT INTO countries(country_id, display_name) VALUES("hti","haiti");
INSERT INTO countries(country_id, display_name) VALUES("hun","hungary");
INSERT INTO countries(country_id, display_name) VALUES("ind","india");
INSERT INTO countries(country_id, display_name) VALUES("irl","ireland");
INSERT INTO countries(country_id, display_name) VALUES("irn","iran");
INSERT INTO countries(country_id, display_name) VALUES("irq","iraq");
INSERT INTO countries(country_id, display_name) VALUES("isl","iceland");
INSERT INTO countries(country_id, display_name) VALUES("ita","italy");
INSERT INTO countries(country_id, display_name) VALUES("jam","jamaica");
INSERT INTO countries(country_id, display_name) VALUES("jpn","japan");
INSERT INTO countries(country_id, display_name) VALUES("khm","cambodia");
INSERT INTO countries(country_id, display_name) VALUES("kor","korea");
INSERT INTO countries(country_id, display_name) VALUES("kwt","kuwait");
INSERT INTO countries(country_id, display_name) VALUES("lbn","lebanon");
INSERT INTO countries(country_id, display_name) VALUES("lbr","liberia");
INSERT INTO countries(country_id, display_name) VALUES("lie","liechtenstein");
INSERT INTO countries(country_id, display_name) VALUES("ltu","lithuania");
INSERT INTO countries(country_id, display_name) VALUES("lux","luxembourg");
INSERT INTO countries(country_id, display_name) VALUES("lva","latvia");
INSERT INTO countries(country_id, display_name) VALUES("mac","macau");
INSERT INTO countries(country_id, display_name) VALUES("mar","morocco");
INSERT INTO countries(country_id, display_name) VALUES("mex","mexico");
INSERT INTO countries(country_id, display_name) VALUES("mmr","myanmar");
INSERT INTO countries(country_id, display_name) VALUES("mng","mongolia");
INSERT INTO countries(country_id, display_name) VALUES("nld","netherlands, the");
INSERT INTO countries(country_id, display_name) VALUES("nor","norway");
INSERT INTO countries(country_id, display_name) VALUES("npl","nepal");
INSERT INTO countries(country_id, display_name) VALUES("nzl","new zealand");
INSERT INTO countries(country_id, display_name) VALUES("pan","panama");
INSERT INTO countries(country_id, display_name) VALUES("per","peru");
INSERT INTO countries(country_id, display_name) VALUES("phl","philippines");
INSERT INTO countries(country_id, display_name) VALUES("pol","poland");
INSERT INTO countries(country_id, display_name) VALUES("prt","portugal");
INSERT INTO countries(country_id, display_name) VALUES("pry","paraguay");
INSERT INTO countries(country_id, display_name) VALUES("rou","romania");
INSERT INTO countries(country_id, display_name) VALUES("rus","russia");
INSERT INTO countries(country_id, display_name) VALUES("sau","saudi arabia");
INSERT INTO countries(country_id, display_name) VALUES("slv","el salvador");
INSERT INTO countries(country_id, display_name) VALUES("srb","serbia");
INSERT INTO countries(country_id, display_name) VALUES("sur","suriname");
INSERT INTO countries(country_id, display_name) VALUES("swe","sweden");
INSERT INTO countries(country_id, display_name) VALUES("syr","syria");
INSERT INTO countries(country_id, display_name) VALUES("tha","thailand");
INSERT INTO countries(country_id, display_name) VALUES("tur","turkey");
INSERT INTO countries(country_id, display_name) VALUES("ury","uruguay");
INSERT INTO countries(country_id, display_name) VALUES("usa","united states of america");
INSERT INTO countries(country_id, display_name) VALUES("ven","venezuela");
INSERT INTO countries(country_id, display_name) VALUES("zaf","south africa");
INSERT INTO country_names(name,country_id) VALUES("afghanistan","afg");
INSERT INTO country_names(name,country_id) VALUES("afghan","afg");
INSERT INTO country_names(name,country_id) VALUES("afghani","afg");
INSERT INTO country_names(name,country_id) VALUES("afghanistani","afg");
INSERT INTO country_names(name,country_id) VALUES("islamic emirate of afghanistan","afg");
INSERT INTO country_names(name,country_id) VALUES("albania","alb");
INSERT INTO country_names(name,country_id) VALUES("albanian","alb");
INSERT INTO country_names(name,country_id) VALUES("shqiperise","alb");
INSERT INTO country_names(name,country_id) VALUES("republic of albania","alb");
INSERT INTO country_names(name,country_id) VALUES("republika e shqiperise","alb");
INSERT INTO country_names(name,country_id) VALUES("argentina","arg");
INSERT INTO country_names(name,country_id) VALUES("argentine","arg");
INSERT INTO country_names(name,country_id) VALUES("argentine republic","arg");
INSERT INTO country_names(name,country_id) VALUES("republica argentina","arg");
INSERT INTO country_names(name,country_id) VALUES("australia","aus");
INSERT INTO country_names(name,country_id) VALUES("australian","aus");
INSERT INTO country_names(name,country_id) VALUES("commonwealth of autralia","aus");
INSERT INTO country_names(name,country_id) VALUES("austria","aut");
INSERT INTO country_names(name,country_id) VALUES("austrian","aut");
INSERT INTO country_names(name,country_id) VALUES("republic of austria","aut");
INSERT INTO country_names(name,country_id) VALUES("osterreich","aut");
INSERT INTO country_names(name,country_id) VALUES("republik osterreich","aut");
INSERT INTO country_names(name,country_id) VALUES("belgium","bel");
INSERT INTO country_names(name,country_id) VALUES("belgian","bel");
INSERT INTO country_names(name,country_id) VALUES("kingdom of belgium","bel");
INSERT INTO country_names(name,country_id) VALUES("belgie","bel");
INSERT INTO country_names(name,country_id) VALUES("belgique","bel");
INSERT INTO country_names(name,country_id) VALUES("belgien","bel");
INSERT INTO country_names(name,country_id) VALUES("bulgaria","bgr");
INSERT INTO country_names(name,country_id) VALUES("bulgarian","bgr");
INSERT INTO country_names(name,country_id) VALUES("republic of bulgaria","bgr");
INSERT INTO country_names(name,country_id) VALUES("bulgariya","bgr");
INSERT INTO country_names(name,country_id) VALUES("republika bulgariya","bgr");
INSERT INTO country_names(name,country_id) VALUES("bermuda","bmu");
INSERT INTO country_names(name,country_id) VALUES("bermudian","bmu");
INSERT INTO country_names(name,country_id) VALUES("bermy","bmu");
INSERT INTO country_names(name,country_id) VALUES("bolivia","bol");
INSERT INTO country_names(name,country_id) VALUES("bolivian","bol");
INSERT INTO country_names(name,country_id) VALUES("plurinational state of bolivia","bol");
INSERT INTO country_names(name,country_id) VALUES("estada plurinacional de bolivia","bol");
INSERT INTO country_names(name,country_id) VALUES("brazil","bra");
INSERT INTO country_names(name,country_id) VALUES("brazilian","bra");
INSERT INTO country_names(name,country_id) VALUES("brasil","bra");
INSERT INTO country_names(name,country_id) VALUES("federative republic of brazil","bra");
INSERT INTO country_names(name,country_id) VALUES("republica federativa do brasil","bra");
INSERT INTO country_names(name,country_id) VALUES("republic of brazil","bra");
INSERT INTO country_names(name,country_id) VALUES("canada","can");
INSERT INTO country_names(name,country_id) VALUES("canadian","can");
INSERT INTO country_names(name,country_id) VALUES("switzerland","che");
INSERT INTO country_names(name,country_id) VALUES("swiss","che");
INSERT INTO country_names(name,country_id) VALUES("helvetia","che");
INSERT INTO country_names(name,country_id) VALUES("confoederatio helvetica","che");
INSERT INTO country_names(name,country_id) VALUES("chile","chl");
INSERT INTO country_names(name,country_id) VALUES("republic of chile","chl");
INSERT INTO country_names(name,country_id) VALUES("republica de chile","chl");
INSERT INTO country_names(name,country_id) VALUES("china","chn");
INSERT INTO country_names(name,country_id) VALUES("chinese","chn");
INSERT INTO country_names(name,country_id) VALUES("republic of china","chn");
INSERT INTO country_names(name,country_id) VALUES("people's republic of china","chn");
INSERT INTO country_names(name,country_id) VALUES("peoples republic of china","chn");
INSERT INTO country_names(name,country_id) VALUES("colombia","col");
INSERT INTO country_names(name,country_id) VALUES("colombian","col");
INSERT INTO country_names(name,country_id) VALUES("republic of colombia","col");
INSERT INTO country_names(name,country_id) VALUES("republica de colombia","col");
INSERT INTO country_names(name,country_id) VALUES("comoros","com");
INSERT INTO country_names(name,country_id) VALUES("union of the comoros","com");
INSERT INTO country_names(name,country_id) VALUES("komori","com");
INSERT INTO country_names(name,country_id) VALUES("comores","com");
INSERT INTO country_names(name,country_id) VALUES("udzima wa komori","com");
INSERT INTO country_names(name,country_id) VALUES("union des comores","com");
INSERT INTO country_names(name,country_id) VALUES("costa rica","cri");
INSERT INTO country_names(name,country_id) VALUES("costa rican","cri");
INSERT INTO country_names(name,country_id) VALUES("republic of costa rica","cri");
INSERT INTO country_names(name,country_id) VALUES("republica de costa rica","cri");
INSERT INTO country_names(name,country_id) VALUES("czechoslovakia","csk");
INSERT INTO country_names(name,country_id) VALUES("czechoslovakian","csk");
INSERT INTO country_names(name,country_id) VALUES("ceskoslovensko","csk");
INSERT INTO country_names(name,country_id) VALUES("cuba","cub");
INSERT INTO country_names(name,country_id) VALUES("cuban","cub");
INSERT INTO country_names(name,country_id) VALUES("republic of cuba","cub");
INSERT INTO country_names(name,country_id) VALUES("republica de cuba","cub");
INSERT INTO country_names(name,country_id) VALUES("curacao","cuw");
INSERT INTO country_names(name,country_id) VALUES("country of curacao","cuw");
INSERT INTO country_names(name,country_id) VALUES("korsou","cuw");
INSERT INTO country_names(name,country_id) VALUES("land curacao","cuw");
INSERT INTO country_names(name,country_id) VALUES("pais korsou","cuw");
INSERT INTO country_names(name,country_id) VALUES("Cyprus","cyp");
INSERT INTO country_names(name,country_id) VALUES("cypriot","cyp");
INSERT INTO country_names(name,country_id) VALUES("republic of cyprus","cyp");
INSERT INTO country_names(name,country_id) VALUES("germany","deu");
INSERT INTO country_names(name,country_id) VALUES("german","deu");
INSERT INTO country_names(name,country_id) VALUES("deutschland","deu");
INSERT INTO country_names(name,country_id) VALUES("denmark","dnk");
INSERT INTO country_names(name,country_id) VALUES("danish","dnk");
INSERT INTO country_names(name,country_id) VALUES("danmark","dnk");
INSERT INTO country_names(name,country_id) VALUES("ecuador","ecu");
INSERT INTO country_names(name,country_id) VALUES("ecuadorian","ecu");
INSERT INTO country_names(name,country_id) VALUES("republic of ecuador","ecu");
INSERT INTO country_names(name,country_id) VALUES("republica del ecuador","ecu");
INSERT INTO country_names(name,country_id) VALUES("egypt","egy");
INSERT INTO country_names(name,country_id) VALUES("egyptian","egy");
INSERT INTO country_names(name,country_id) VALUES("arab republic of egypt","egy");
INSERT INTO country_names(name,country_id) VALUES("eritrea","eri");
INSERT INTO country_names(name,country_id) VALUES("state of eritrea","eri");
INSERT INTO country_names(name,country_id) VALUES("eritrean","eri");
INSERT INTO country_names(name,country_id) VALUES("spain","esp");
INSERT INTO country_names(name,country_id) VALUES("spanish","esp");
INSERT INTO country_names(name,country_id) VALUES("kingdom of spain","esp");
INSERT INTO country_names(name,country_id) VALUES("espana","esp");
INSERT INTO country_names(name,country_id) VALUES("reino de espana","esp");
INSERT INTO country_names(name,country_id) VALUES("estonia","est");
INSERT INTO country_names(name,country_id) VALUES("republic of estonia","est");
INSERT INTO country_names(name,country_id) VALUES("eesti","est");
INSERT INTO country_names(name,country_id) VALUES("eesti vabariik","est");
INSERT INTO country_names(name,country_id) VALUES("estonian","est");
INSERT INTO country_names(name,country_id) VALUES("ethiopia","eth");
INSERT INTO country_names(name,country_id) VALUES("ethiopian","eth");
INSERT INTO country_names(name,country_id) VALUES("federal democratic republic of ethiopia","eth");
INSERT INTO country_names(name,country_id) VALUES("finland","fin");
INSERT INTO country_names(name,country_id) VALUES("republic of finland","fin");
INSERT INTO country_names(name,country_id) VALUES("finnish","fin");
INSERT INTO country_names(name,country_id) VALUES("suomi","fin");
INSERT INTO country_names(name,country_id) VALUES("suomen tasavalta","fin");
INSERT INTO country_names(name,country_id) VALUES("republiken finland","fin");
INSERT INTO country_names(name,country_id) VALUES("fiji","fji");
INSERT INTO country_names(name,country_id) VALUES("republic of fiji","fji");
INSERT INTO country_names(name,country_id) VALUES("fijian","fji");
INSERT INTO country_names(name,country_id) VALUES("france","fra");
INSERT INTO country_names(name,country_id) VALUES("french","fra");
INSERT INTO country_names(name,country_id) VALUES("francais","fra");
INSERT INTO country_names(name,country_id) VALUES("francaise","fra");
INSERT INTO country_names(name,country_id) VALUES("great britain","gbr");
INSERT INTO country_names(name,country_id) VALUES("britain","gbr");
INSERT INTO country_names(name,country_id) VALUES("british","gbr");
INSERT INTO country_names(name,country_id) VALUES("greece","grc");
INSERT INTO country_names(name,country_id) VALUES("greek","grc");
INSERT INTO country_names(name,country_id) VALUES("hellenic republic","grc");
INSERT INTO country_names(name,country_id) VALUES("elliniki dimokratia","grc");
INSERT INTO country_names(name,country_id) VALUES("guatemala","gtm");
INSERT INTO country_names(name,country_id) VALUES("guatemalan","gtm");
INSERT INTO country_names(name,country_id) VALUES("republic of guatemala","gtm");
INSERT INTO country_names(name,country_id) VALUES("republica de guatemala","gtm");
INSERT INTO country_names(name,country_id) VALUES("hawaii","haw");
INSERT INTO country_names(name,country_id) VALUES("hawaiian","haw");
INSERT INTO country_names(name,country_id) VALUES("hong kong","hkg");
INSERT INTO country_names(name,country_id) VALUES("hk","hkg");
INSERT INTO country_names(name,country_id) VALUES("honduras","hnd");
INSERT INTO country_names(name,country_id) VALUES("republic of honduras","hnd");
INSERT INTO country_names(name,country_id) VALUES("republica de honduras","hnd");
INSERT INTO country_names(name,country_id) VALUES("haiti","hti");
INSERT INTO country_names(name,country_id) VALUES("haitian","hti");
INSERT INTO country_names(name,country_id) VALUES("republic of haiti","hti");
INSERT INTO country_names(name,country_id) VALUES("ayiti","hti");
INSERT INTO country_names(name,country_id) VALUES("repiblik d ayiti","hti");
INSERT INTO country_names(name,country_id) VALUES("hungary","hun");
INSERT INTO country_names(name,country_id) VALUES("hungarian","hun");
INSERT INTO country_names(name,country_id) VALUES("magyarorszag","hun");
INSERT INTO country_names(name,country_id) VALUES("india","ind");
INSERT INTO country_names(name,country_id) VALUES("indian","ind");
INSERT INTO country_names(name,country_id) VALUES("republic of india","ind");
INSERT INTO country_names(name,country_id) VALUES("ireland","irl");
INSERT INTO country_names(name,country_id) VALUES("eire","irl");
INSERT INTO country_names(name,country_id) VALUES("irish","irl");
INSERT INTO country_names(name,country_id) VALUES("republic of ireland","irl");
INSERT INTO country_names(name,country_id) VALUES("iran","irn");
INSERT INTO country_names(name,country_id) VALUES("irani","irn");
INSERT INTO country_names(name,country_id) VALUES("islamic republic of iran","irn");
INSERT INTO country_names(name,country_id) VALUES("republic of iran","irn");
INSERT INTO country_names(name,country_id) VALUES("iraq","irq");
INSERT INTO country_names(name,country_id) VALUES("republic of iraq","irq");
INSERT INTO country_names(name,country_id) VALUES("iraqi","irq");
INSERT INTO country_names(name,country_id) VALUES("iceland","isl");
INSERT INTO country_names(name,country_id) VALUES("island","isl");
INSERT INTO country_names(name,country_id) VALUES("icelandish","isl");
INSERT INTO country_names(name,country_id) VALUES("icelandic","isl");
INSERT INTO country_names(name,country_id) VALUES("italy","ita");
INSERT INTO country_names(name,country_id) VALUES("italian","ita");
INSERT INTO country_names(name,country_id) VALUES("jamaica","jam");
INSERT INTO country_names(name,country_id) VALUES("jamaican","jam");
INSERT INTO country_names(name,country_id) VALUES("jumieka","jam");
INSERT INTO country_names(name,country_id) VALUES("japan","jpn");
INSERT INTO country_names(name,country_id) VALUES("japanese","jpn");
INSERT INTO country_names(name,country_id) VALUES("nihon","jpn");
INSERT INTO country_names(name,country_id) VALUES("nippon","jpn");
INSERT INTO country_names(name,country_id) VALUES("nihon-koku","jpn");
INSERT INTO country_names(name,country_id) VALUES("nippon-koku","jpn");
INSERT INTO country_names(name,country_id) VALUES("cambodia","khm");
INSERT INTO country_names(name,country_id) VALUES("cambodian","khm");
INSERT INTO country_names(name,country_id) VALUES("kingdom of cambodia","khm");
INSERT INTO country_names(name,country_id) VALUES("korea","kor");
INSERT INTO country_names(name,country_id) VALUES("korean","kor");
INSERT INTO country_names(name,country_id) VALUES("republic of korean","kor");
INSERT INTO country_names(name,country_id) VALUES("south korea","kor");
INSERT INTO country_names(name,country_id) VALUES("s korea","kor");
INSERT INTO country_names(name,country_id) VALUES("s. korea","kor");
INSERT INTO country_names(name,country_id) VALUES("kuwait","kwt");
INSERT INTO country_names(name,country_id) VALUES("state of kuwait","kwt");
INSERT INTO country_names(name,country_id) VALUES("lebanon","lbn");
INSERT INTO country_names(name,country_id) VALUES("lebanese","lbn");
INSERT INTO country_names(name,country_id) VALUES("republic of lebanon","lbn");
INSERT INTO country_names(name,country_id) VALUES("liberia","lbr");
INSERT INTO country_names(name,country_id) VALUES("liberian","lbr");
INSERT INTO country_names(name,country_id) VALUES("republic of liberia","lbr");
INSERT INTO country_names(name,country_id) VALUES("liechtenstein","lie");
INSERT INTO country_names(name,country_id) VALUES("principality of liechtenstein","lie");
INSERT INTO country_names(name,country_id) VALUES("furstentum liechtenstein","lie");
INSERT INTO country_names(name,country_id) VALUES("lithuania","ltu");
INSERT INTO country_names(name,country_id) VALUES("republic of lithuania","ltu");
INSERT INTO country_names(name,country_id) VALUES("lietuvos","ltu");
INSERT INTO country_names(name,country_id) VALUES("lietuvos respublika","ltu");
INSERT INTO country_names(name,country_id) VALUES("lithuanian","ltu");
INSERT INTO country_names(name,country_id) VALUES("luxembourg","lux");
INSERT INTO country_names(name,country_id) VALUES("letzeburg","lux");
INSERT INTO country_names(name,country_id) VALUES("grand duchy of luxembourg","lux");
INSERT INTO country_names(name,country_id) VALUES("latvia","lva");
INSERT INTO country_names(name,country_id) VALUES("latvian","lva");
INSERT INTO country_names(name,country_id) VALUES("republic of latvia","lva");
INSERT INTO country_names(name,country_id) VALUES("latvijas","lva");
INSERT INTO country_names(name,country_id) VALUES("latvejas","lva");
INSERT INTO country_names(name,country_id) VALUES("macau","mac");
INSERT INTO country_names(name,country_id) VALUES("macao","mac");
INSERT INTO country_names(name,country_id) VALUES("morocco","mar");
INSERT INTO country_names(name,country_id) VALUES("moroccan","mar");
INSERT INTO country_names(name,country_id) VALUES("kingdom of morocco","mar");
INSERT INTO country_names(name,country_id) VALUES("mexico","mex");
INSERT INTO country_names(name,country_id) VALUES("mexican","mex");
INSERT INTO country_names(name,country_id) VALUES("myanmar","mmr");
INSERT INTO country_names(name,country_id) VALUES("burma","mmr");
INSERT INTO country_names(name,country_id) VALUES("burmese","mmr");
INSERT INTO country_names(name,country_id) VALUES("union of myanmar","mmr");
INSERT INTO country_names(name,country_id) VALUES("republic of the union of myanmar","mmr");
INSERT INTO country_names(name,country_id) VALUES("republic of myanmar","mmr");
INSERT INTO country_names(name,country_id) VALUES("mongolia","mng");
INSERT INTO country_names(name,country_id) VALUES("mongolian","mng");
INSERT INTO country_names(name,country_id) VALUES("netherlands, the","nld");
INSERT INTO country_names(name,country_id) VALUES("netherland","nld");
INSERT INTO country_names(name,country_id) VALUES("kingdom of the netherlands","nld");
INSERT INTO country_names(name,country_id) VALUES("netherlands","nld");
INSERT INTO country_names(name,country_id) VALUES("the netherlands","nld");
INSERT INTO country_names(name,country_id) VALUES("dutch","nld");
INSERT INTO country_names(name,country_id) VALUES("norway","nor");
INSERT INTO country_names(name,country_id) VALUES("norwegian","nor");
INSERT INTO country_names(name,country_id) VALUES("kingdom of norway","nor");
INSERT INTO country_names(name,country_id) VALUES("norge","nor");
INSERT INTO country_names(name,country_id) VALUES("noreg","nor");
INSERT INTO country_names(name,country_id) VALUES("kongeriket norge","nor");
INSERT INTO country_names(name,country_id) VALUES("nepal","npl");
INSERT INTO country_names(name,country_id) VALUES("nepalese","npl");
INSERT INTO country_names(name,country_id) VALUES("federal democratic republic of nepal","npl");
INSERT INTO country_names(name,country_id) VALUES("republic of nepal","npl");
INSERT INTO country_names(name,country_id) VALUES("nepala","npl");
INSERT INTO country_names(name,country_id) VALUES("democratic republic of nepal","npl");
INSERT INTO country_names(name,country_id) VALUES("new zealand","nzl");
INSERT INTO country_names(name,country_id) VALUES("zealand","nzl");
INSERT INTO country_names(name,country_id) VALUES("aotearoa","nzl");
INSERT INTO country_names(name,country_id) VALUES("panama","pan");
INSERT INTO country_names(name,country_id) VALUES("panamanian","pan");
INSERT INTO country_names(name,country_id) VALUES("republic of panama","pan");
INSERT INTO country_names(name,country_id) VALUES("republica de panama","pan");
INSERT INTO country_names(name,country_id) VALUES("peru","per");
INSERT INTO country_names(name,country_id) VALUES("peruvian","per");
INSERT INTO country_names(name,country_id) VALUES("republic of peru","per");
INSERT INTO country_names(name,country_id) VALUES("republica del peru","per");
INSERT INTO country_names(name,country_id) VALUES("philippines","phl");
INSERT INTO country_names(name,country_id) VALUES("the philippines","phl");
INSERT INTO country_names(name,country_id) VALUES("filipino","phl");
INSERT INTO country_names(name,country_id) VALUES("republic of the philippines","phl");
INSERT INTO country_names(name,country_id) VALUES("the republic of the philippines","phl");
INSERT INTO country_names(name,country_id) VALUES("pilipinas","phl");
INSERT INTO country_names(name,country_id) VALUES("poland","pol");
INSERT INTO country_names(name,country_id) VALUES("polish","pol");
INSERT INTO country_names(name,country_id) VALUES("republic of poland","pol");
INSERT INTO country_names(name,country_id) VALUES("rzeczpospolita polska","pol");
INSERT INTO country_names(name,country_id) VALUES("polska","pol");
INSERT INTO country_names(name,country_id) VALUES("portugal","prt");
INSERT INTO country_names(name,country_id) VALUES("portuguese","prt");
INSERT INTO country_names(name,country_id) VALUES("portuguese republic","prt");
INSERT INTO country_names(name,country_id) VALUES("republica portuguesa","prt");
INSERT INTO country_names(name,country_id) VALUES("republica pertuesa","prt");
INSERT INTO country_names(name,country_id) VALUES("portuguesa","prt");
INSERT INTO country_names(name,country_id) VALUES("paraguay","pry");
INSERT INTO country_names(name,country_id) VALUES("republic of paraguay","pry");
INSERT INTO country_names(name,country_id) VALUES("republica del paraguay","pry");
INSERT INTO country_names(name,country_id) VALUES("paraguai","pry");
INSERT INTO country_names(name,country_id) VALUES("paraguai tavakuaireta","pry");
INSERT INTO country_names(name,country_id) VALUES("romania","rou");
INSERT INTO country_names(name,country_id) VALUES("romanian","rou");
INSERT INTO country_names(name,country_id) VALUES("russia","rus");
INSERT INTO country_names(name,country_id) VALUES("russian","rus");
INSERT INTO country_names(name,country_id) VALUES("saudi arabia","sau");
INSERT INTO country_names(name,country_id) VALUES("saudi arabian","sau");
INSERT INTO country_names(name,country_id) VALUES("saudi","sau");
INSERT INTO country_names(name,country_id) VALUES("kingdom of saudi arabia","sau");
INSERT INTO country_names(name,country_id) VALUES("el salvador","slv");
INSERT INTO country_names(name,country_id) VALUES("republic of el salvador","slv");
INSERT INTO country_names(name,country_id) VALUES("republica de el salvador","slv");
INSERT INTO country_names(name,country_id) VALUES("el salvadorean","slv");
INSERT INTO country_names(name,country_id) VALUES("salvadorean","slv");
INSERT INTO country_names(name,country_id) VALUES("serbia","srb");
INSERT INTO country_names(name,country_id) VALUES("serbian","srb");
INSERT INTO country_names(name,country_id) VALUES("republic of serbia","srb");
INSERT INTO country_names(name,country_id) VALUES("republika srbija","srb");
INSERT INTO country_names(name,country_id) VALUES("srbija","srb");
INSERT INTO country_names(name,country_id) VALUES("suriname","sur");
INSERT INTO country_names(name,country_id) VALUES("republic of suriname","sur");
INSERT INTO country_names(name,country_id) VALUES("republiek suriname","sur");
INSERT INTO country_names(name,country_id) VALUES("dutch guiana","sur");
INSERT INTO country_names(name,country_id) VALUES("guiana","sur");
INSERT INTO country_names(name,country_id) VALUES("sweden","swe");
INSERT INTO country_names(name,country_id) VALUES("swedish","swe");
INSERT INTO country_names(name,country_id) VALUES("kingdom of sweden","swe");
INSERT INTO country_names(name,country_id) VALUES("konungariket sverige","swe");
INSERT INTO country_names(name,country_id) VALUES("syria","syr");
INSERT INTO country_names(name,country_id) VALUES("syrian","syr");
INSERT INTO country_names(name,country_id) VALUES("syrian arab republic","syr");
INSERT INTO country_names(name,country_id) VALUES("thailand","tha");
INSERT INTO country_names(name,country_id) VALUES("thai","tha");
INSERT INTO country_names(name,country_id) VALUES("kingdom of thailand","tha");
INSERT INTO country_names(name,country_id) VALUES("turkey","tur");
INSERT INTO country_names(name,country_id) VALUES("turkiye","tur");
INSERT INTO country_names(name,country_id) VALUES("turkish","tur");
INSERT INTO country_names(name,country_id) VALUES("republic of turkey","tur");
INSERT INTO country_names(name,country_id) VALUES("republic of turkiye","tur");
INSERT INTO country_names(name,country_id) VALUES("turkiye cumhuriyeti","tur");
INSERT INTO country_names(name,country_id) VALUES("uruguay","ury");
INSERT INTO country_names(name,country_id) VALUES("uruguai","ury");
INSERT INTO country_names(name,country_id) VALUES("oriental republic of uruguay","ury");
INSERT INTO country_names(name,country_id) VALUES("republic of uruguay","ury");
INSERT INTO country_names(name,country_id) VALUES("republica oriental del uruguay","ury");
INSERT INTO country_names(name,country_id) VALUES("republica oriental do uruguai","ury");
INSERT INTO country_names(name,country_id) VALUES("united states of america","usa");
INSERT INTO country_names(name,country_id) VALUES("usa","usa");
INSERT INTO country_names(name,country_id) VALUES("us","usa");
INSERT INTO country_names(name,country_id) VALUES("united states","usa");
INSERT INTO country_names(name,country_id) VALUES("united states america","usa");
INSERT INTO country_names(name,country_id) VALUES("venezuela","ven");
INSERT INTO country_names(name,country_id) VALUES("venezuelan","ven");
INSERT INTO country_names(name,country_id) VALUES("bolivarian republic of venezuela","ven");
INSERT INTO country_names(name,country_id) VALUES("republica bolivariana de venezuela","ven");
INSERT INTO country_names(name,country_id) VALUES("south africa","zaf");
INSERT INTO country_names(name,country_id) VALUES("south african","zaf");
INSERT INTO country_names(name,country_id) VALUES("s africa","zaf");
INSERT INTO country_names(name,country_id) VALUES("s. africa","zaf");
INSERT INTO country_names(name,country_id) VALUES("s african","zaf");
INSERT INTO country_names(name,country_id) VALUES("s. african","zaf");
INSERT INTO countries(country_id,display_name) VALUES("isr","israel");INSERT INTO country_names(country_id,name) VALUES("isr","israel");INSERT INTO country_names(country_id,name) VALUES("isr","israeli");INSERT INTO country_names(country_id,name) VALUES("isr","state of israel");
