insert into countries(country_id,name,alternative_name_1) values("can","canada","canadian");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("fra","france","french","francais","francaise");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("deu","germany","german","deutschland");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("gbr","great britain","britain","british");
insert into countries(country_id,name,alternative_name_1) values("ita","italy","italian");
insert into countries(country_id,name,alternative_name_1) values("mex","mexico","mexican");
insert into countries(country_id,name,alternative_name_1) values("rus","russia","russian");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("zaf","south africa","south african","s africa","s. africa","s african","s. african");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("che","switzerland","swiss","helvetia","confoederatio helvetica");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("usa","united states of america","usa","us","united states","united states america");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("sur","suriname","republic of suriname","republiek suriname","dutch guiana","guiana");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) values("srb","serbia","serbian","republic of serbia","republika srbija","srbija");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("lva","latvia","latvian","republic of latvia","latvijas","latvejas");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("hti","haiti","haitian","republic of haiti","ayiti","repiblik d ayiti");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lux","luxembourg","letzeburg","grand duchy of luxembourg");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("cub","cuba","cuban","republic of cuba","republica de cuba");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("cuw","curacao","country of curacao","korsou","land curacao","pais korsou");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("cyp","Cyprus","cypriot","republic of cyprus");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("arg","argentina","argentine","argentine republic","republica argentina");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("aus","australia","australian","commonwealth of autralia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("hnd","honduras","republic of honduras","republica de honduras");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("hkg","hong kong","hk");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("isl","iceland","island","icelandish","icelandic");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("ind","india","indian","republic of india");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("irl","ireland","eire","irish","republic of ireland");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("jam","jamaica","jamaican","jumieka");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("kwt","kuwait","state of kuwait");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lbn","lebanon","lebanese","republic of lebanon");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("lbr","liberia","liberian","republic of liberia");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("mac","macau","macao");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("pry","paraguay","republic of paraguay","republica del paraguay","paraguai","paraguai tavakuaireta");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("col","colombia","colombian","republic of colombia","republica de colombia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("com","comoros","union of the comoros","komori","comores","udzima wa komori","union des comores");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("grc","greece","greek","hellenic republic","elliniki dimokratia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("pol","poland","polish","republic of poland","rzeczpospolita polska","polska");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("esp","spain","spanish","kingdom of spain","espana","reino de espana");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("bel","belgium","belgian","kingdom of belgium","belgie","belgique","belgien");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("aut","austria","austrian","republic of austria","osterreich","republik osterreich");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("dnk","denmark","danish","danmark");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("egy","egypt","egyptian","arab republic of egypt");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("fin","finland","republic of finland","finnish","suomi","suomen tasavalta","republiken finland");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("gbr","great britain","britain","british");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("nld","netherlands, the","netherland","kingdom of the netherlands","netherlands","the netherlands","dutch");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("swe","sweden","swedish","kingdom of sweden","konungariket sverige");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("ven","venezuela","venezuelan","bolivarian republic of venezuela","republica bolivariana de venezuela");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("jpn","japan","japanese","nihon","nippon","nihon-koku","nippon-koku");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("haw","hawaii","hawaiian");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("khm","cambodia","cambodian","kingdom of cambodia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("bol","bolivia","bolivian","plurinational state of bolivia","estada plurinacional de bolivia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("bra","brazil","brazilian","brasil","federative republic of brazil","republica federativa do brasil","republic of brazil");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("bgr","bulgaria","bulgarian","republic of bulgaria","bulgariya","republika bulgariya");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("mmr","myanmar","burma","burmese","union of myanmar","republic of the union of myanmar","republic of myanmar");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("chn","china","chinese","republic of china","people's republic of china","peoples republic of china");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("cri","costa rica","costa rican","republic of costa rica","republica de costa rica");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("hun","hungary","hungarian","magyarorszag");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("nor","norway","norwegian","kingdom of norway","norge","noreg","kongeriket norge");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("per","peru","peruvian","republic of peru","republica del peru");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("prt","portugal","portuguese","portuguese republic","republica portuguesa","republica pertuesa","portuguesa");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("rou","romania","romanian");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("afg","afghanistan","afghan","afghani","afghanistani","islamic emirate of afghanistan");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("alb","albania","albanian","shqiperise","republic of albania","republika e shqiperise");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("bmu","bermuda","bermudian","bermy");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("chl","chile","republic of chile","republica de chile");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("csk","czechoslovakia","czechoslovakian","ceskoslovensko");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("ecu","ecuador","ecuadorian","republic of ecuador","republica del ecuador");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("slv","el salvador","republic of el salvador","republica de el salvador","el salvadorean","salvadorean");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("eri","eritrea","state of eritrea","eritrean");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("est","estonia","republic of estonia","eesti","eesti vabariik","estonian");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("fji","fiji","republic of fiji","fijian");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("irq","iraq","republic of iraq","iraqi");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4) VALUES("ltu","lithuania","republic of lithuania","lietuvos","lietuvos respublika","lithuanian");
INSERT INTO countries(country_id,name,alternative_name_1) VALUES("mng","mongolia","mongolian");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("pan","panama","panamanian","republic of panama","republica de panama");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) VALUES("phl","philippines","the philippines","filipino","republic of the philippines","the republic of the philippines","pilipinas");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) VALUES("sau","saudi arabia","saudi arabian","saudi","kingdom of saudi arabia");
INSERT INTO countries(country_id,name,alternative_name_1,alternative_name_2) VALUES("syr","syria","syrian","syrian arab republic");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("eth","ethiopia","ethiopian","federal democratic republic of ethiopia");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("gtm","guatemala","guatemalan","republic of guatemala","republica de guatemala");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3) values("irn","iran","irani","islamic republic of iran","republic of iran");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("kor","korea","korean","republic of korean","south korea","s korea","s. korea");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("lie","liechtenstein","principality of liechtenstein","furstentum liechtenstein");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("mar","morocco","moroccan","kingdom of morocco");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("npl","nepal","nepalese","federal democratic republic of nepal","republic of nepal","nepala","democratic republic of nepal");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("nzl","new zealand","zealand","aotearoa");
insert into countries(country_id,name,alternative_name_1,alternative_name_2) values("tha","thailand","thai","kingdom of thailand");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("tur","turkey","turkiye","turkish","republic of turkey","republic of turkiye","turkiye cumhuriyeti");
insert into countries(country_id,name,alternative_name_1,alternative_name_2,alternative_name_3,alternative_name_4,alternative_name_5) values("ury","uruguay","uruguai","oriental republic of uruguay","republic of uruguay","republica oriental del uruguay","republica oriental do uruguai");
