INSERT INTO countries(country_id, display_name, tags) VALUES('afg', 'afghanistan', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('alb', 'albania', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('arg', 'argentina', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('aus', 'australia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('aut', 'austria', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('bel', 'belgium', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('bgr', 'bulgaria', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('bmu', 'bermuda', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('bol', 'bolivia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('bra', 'brazil', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('can', 'canada', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('che', 'switzerland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('chl', 'chile', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('chn', 'china', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('col', 'colombia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('com', 'comoros', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('cri', 'costa rica', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('csk', 'czechoslovakia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('cub', 'cuba', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('cuw', 'curacao', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('cyp', 'Cyprus', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('deu', 'germany', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('dnk', 'denmark', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ecu', 'ecuador', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('egy', 'egypt', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('eri', 'eritrea', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('esp', 'spain', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('est', 'estonia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('eth', 'ethiopia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('fin', 'finland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('fji', 'fiji', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('fra', 'france', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('gbr', 'great britain', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('grc', 'greece', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('gtm', 'guatemala', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('haw', 'hawaii', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('hkg', 'hong kong', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('hnd', 'honduras', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('hti', 'haiti', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('hun', 'hungary', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ind', 'india', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('irl', 'ireland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('irn', 'iran', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('irq', 'iraq', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('isl', 'iceland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('isr', 'israel', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ita', 'italy', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('jam', 'jamaica', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('jpn', 'japan', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('khm', 'cambodia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('kor', 'korea', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('kwt', 'kuwait', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('lbn', 'lebanon', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('lbr', 'liberia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('lie', 'liechtenstein', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ltu', 'lithuania', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('lux', 'luxembourg', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('lva', 'latvia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('mac', 'macau', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('mar', 'morocco', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('mex', 'mexico', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('mmr', 'myanmar', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('mng', 'mongolia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('nfl', 'newfoundland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('nld', 'netherlands, the', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('nor', 'norway', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('npl', 'nepal', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('nzl', 'new zealand', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('pan', 'panama', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('per', 'peru', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('phl', 'philippines', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('pol', 'poland', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('prt', 'portugal', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('pry', 'paraguay', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('rou', 'romania', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('rus', 'russia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('sau', 'saudi arabia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('slv', 'el salvador', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('srb', 'serbia', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('sur', 'suriname', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('swe', 'sweden', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('syr', 'syria', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('tha', 'thailand', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('tur', 'turkey', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('uar', 'united arab republic', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ury', 'uruguay', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('usa', 'united states of america', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('ven', 'venezuela', 'none');
INSERT INTO countries(country_id, display_name, tags) VALUES('zaf', 'south africa', 'none');
INSERT INTO country_names(country_id, name) VALUES('afg', 'afghan');
INSERT INTO country_names(country_id, name) VALUES('afg', 'afghani');
INSERT INTO country_names(country_id, name) VALUES('afg', 'afghanistan');
INSERT INTO country_names(country_id, name) VALUES('afg', 'afghanistani');
INSERT INTO country_names(country_id, name) VALUES('afg', 'islamic emirate of afghanistan');
INSERT INTO country_names(country_id, name) VALUES('alb', 'albania');
INSERT INTO country_names(country_id, name) VALUES('alb', 'albanian');
INSERT INTO country_names(country_id, name) VALUES('alb', 'republic of albania');
INSERT INTO country_names(country_id, name) VALUES('alb', 'republika e shqiperise');
INSERT INTO country_names(country_id, name) VALUES('alb', 'shqiperise');
INSERT INTO country_names(country_id, name) VALUES('arg', 'argentina');
INSERT INTO country_names(country_id, name) VALUES('arg', 'argentine');
INSERT INTO country_names(country_id, name) VALUES('arg', 'argentine republic');
INSERT INTO country_names(country_id, name) VALUES('arg', 'republica argentina');
INSERT INTO country_names(country_id, name) VALUES('aus', 'australia');
INSERT INTO country_names(country_id, name) VALUES('aus', 'australian');
INSERT INTO country_names(country_id, name) VALUES('aus', 'commonwealth of autralia');
INSERT INTO country_names(country_id, name) VALUES('aut', 'austria');
INSERT INTO country_names(country_id, name) VALUES('aut', 'austrian');
INSERT INTO country_names(country_id, name) VALUES('aut', 'osterreich');
INSERT INTO country_names(country_id, name) VALUES('aut', 'republic of austria');
INSERT INTO country_names(country_id, name) VALUES('aut', 'republik osterreich');
INSERT INTO country_names(country_id, name) VALUES('bel', 'belgian');
INSERT INTO country_names(country_id, name) VALUES('bel', 'belgie');
INSERT INTO country_names(country_id, name) VALUES('bel', 'belgien');
INSERT INTO country_names(country_id, name) VALUES('bel', 'belgique');
INSERT INTO country_names(country_id, name) VALUES('bel', 'belgium');
INSERT INTO country_names(country_id, name) VALUES('bel', 'kingdom of belgium');
INSERT INTO country_names(country_id, name) VALUES('bgr', 'bulgaria');
INSERT INTO country_names(country_id, name) VALUES('bgr', 'bulgarian');
INSERT INTO country_names(country_id, name) VALUES('bgr', 'bulgariya');
INSERT INTO country_names(country_id, name) VALUES('bgr', 'republic of bulgaria');
INSERT INTO country_names(country_id, name) VALUES('bgr', 'republika bulgariya');
INSERT INTO country_names(country_id, name) VALUES('bmu', 'bermuda');
INSERT INTO country_names(country_id, name) VALUES('bmu', 'bermudian');
INSERT INTO country_names(country_id, name) VALUES('bmu', 'bermy');
INSERT INTO country_names(country_id, name) VALUES('bol', 'bolivia');
INSERT INTO country_names(country_id, name) VALUES('bol', 'bolivian');
INSERT INTO country_names(country_id, name) VALUES('bol', 'estada plurinacional de bolivia');
INSERT INTO country_names(country_id, name) VALUES('bol', 'plurinational state of bolivia');
INSERT INTO country_names(country_id, name) VALUES('bra', 'brasil');
INSERT INTO country_names(country_id, name) VALUES('bra', 'brazil');
INSERT INTO country_names(country_id, name) VALUES('bra', 'brazilian');
INSERT INTO country_names(country_id, name) VALUES('bra', 'federative republic of brazil');
INSERT INTO country_names(country_id, name) VALUES('bra', 'republic of brazil');
INSERT INTO country_names(country_id, name) VALUES('bra', 'republica federativa do brasil');
INSERT INTO country_names(country_id, name) VALUES('can', 'canada');
INSERT INTO country_names(country_id, name) VALUES('can', 'canadian');
INSERT INTO country_names(country_id, name) VALUES('che', 'confoederatio helvetica');
INSERT INTO country_names(country_id, name) VALUES('che', 'helvetia');
INSERT INTO country_names(country_id, name) VALUES('che', 'swiss');
INSERT INTO country_names(country_id, name) VALUES('che', 'switzerland');
INSERT INTO country_names(country_id, name) VALUES('chl', 'chile');
INSERT INTO country_names(country_id, name) VALUES('chl', 'republic of chile');
INSERT INTO country_names(country_id, name) VALUES('chl', 'republica de chile');
INSERT INTO country_names(country_id, name) VALUES('chn', 'china');
INSERT INTO country_names(country_id, name) VALUES('chn', 'chinese');
INSERT INTO country_names(country_id, name) VALUES('chn', "people's republic of china");
INSERT INTO country_names(country_id, name) VALUES('chn', 'peoples republic of china');
INSERT INTO country_names(country_id, name) VALUES('chn', 'republic of china');
INSERT INTO country_names(country_id, name) VALUES('col', 'colombia');
INSERT INTO country_names(country_id, name) VALUES('col', 'colombian');
INSERT INTO country_names(country_id, name) VALUES('col', 'republic of colombia');
INSERT INTO country_names(country_id, name) VALUES('col', 'republica de colombia');
INSERT INTO country_names(country_id, name) VALUES('com', 'comores');
INSERT INTO country_names(country_id, name) VALUES('com', 'comoros');
INSERT INTO country_names(country_id, name) VALUES('com', 'komori');
INSERT INTO country_names(country_id, name) VALUES('com', 'udzima wa komori');
INSERT INTO country_names(country_id, name) VALUES('com', 'union des comores');
INSERT INTO country_names(country_id, name) VALUES('com', 'union of the comoros');
INSERT INTO country_names(country_id, name) VALUES('cri', 'costa rica');
INSERT INTO country_names(country_id, name) VALUES('cri', 'costa rican');
INSERT INTO country_names(country_id, name) VALUES('cri', 'republic of costa rica');
INSERT INTO country_names(country_id, name) VALUES('cri', 'republica de costa rica');
INSERT INTO country_names(country_id, name) VALUES('csk', 'ceskoslovensko');
INSERT INTO country_names(country_id, name) VALUES('csk', 'czechoslovakia');
INSERT INTO country_names(country_id, name) VALUES('csk', 'czechoslovakian');
INSERT INTO country_names(country_id, name) VALUES('cub', 'cuba');
INSERT INTO country_names(country_id, name) VALUES('cub', 'cuban');
INSERT INTO country_names(country_id, name) VALUES('cub', 'republic of cuba');
INSERT INTO country_names(country_id, name) VALUES('cub', 'republica de cuba');
INSERT INTO country_names(country_id, name) VALUES('cuw', 'country of curacao');
INSERT INTO country_names(country_id, name) VALUES('cuw', 'curacao');
INSERT INTO country_names(country_id, name) VALUES('cuw', 'korsou');
INSERT INTO country_names(country_id, name) VALUES('cuw', 'land curacao');
INSERT INTO country_names(country_id, name) VALUES('cuw', 'pais korsou');
INSERT INTO country_names(country_id, name) VALUES('cyp', 'cypriot');
INSERT INTO country_names(country_id, name) VALUES('cyp', 'Cyprus');
INSERT INTO country_names(country_id, name) VALUES('cyp', 'republic of cyprus');
INSERT INTO country_names(country_id, name) VALUES('deu', 'deutschland');
INSERT INTO country_names(country_id, name) VALUES('deu', 'german');
INSERT INTO country_names(country_id, name) VALUES('deu', 'germany');
INSERT INTO country_names(country_id, name) VALUES('dnk', 'danish');
INSERT INTO country_names(country_id, name) VALUES('dnk', 'danmark');
INSERT INTO country_names(country_id, name) VALUES('dnk', 'denmark');
INSERT INTO country_names(country_id, name) VALUES('ecu', 'ecuador');
INSERT INTO country_names(country_id, name) VALUES('ecu', 'ecuadorian');
INSERT INTO country_names(country_id, name) VALUES('ecu', 'republic of ecuador');
INSERT INTO country_names(country_id, name) VALUES('ecu', 'republica del ecuador');
INSERT INTO country_names(country_id, name) VALUES('egy', 'arab republic of egypt');
INSERT INTO country_names(country_id, name) VALUES('egy', 'egypt');
INSERT INTO country_names(country_id, name) VALUES('egy', 'egyptian');
INSERT INTO country_names(country_id, name) VALUES('eri', 'eritrea');
INSERT INTO country_names(country_id, name) VALUES('eri', 'eritrean');
INSERT INTO country_names(country_id, name) VALUES('eri', 'state of eritrea');
INSERT INTO country_names(country_id, name) VALUES('esp', 'espana');
INSERT INTO country_names(country_id, name) VALUES('esp', 'kingdom of spain');
INSERT INTO country_names(country_id, name) VALUES('esp', 'reino de espana');
INSERT INTO country_names(country_id, name) VALUES('esp', 'spain');
INSERT INTO country_names(country_id, name) VALUES('esp', 'spanish');
INSERT INTO country_names(country_id, name) VALUES('est', 'eesti');
INSERT INTO country_names(country_id, name) VALUES('est', 'eesti vabariik');
INSERT INTO country_names(country_id, name) VALUES('est', 'estonia');
INSERT INTO country_names(country_id, name) VALUES('est', 'estonian');
INSERT INTO country_names(country_id, name) VALUES('est', 'republic of estonia');
INSERT INTO country_names(country_id, name) VALUES('eth', 'ethiopia');
INSERT INTO country_names(country_id, name) VALUES('eth', 'ethiopian');
INSERT INTO country_names(country_id, name) VALUES('eth', 'federal democratic republic of ethiopia');
INSERT INTO country_names(country_id, name) VALUES('fin', 'finland');
INSERT INTO country_names(country_id, name) VALUES('fin', 'finnish');
INSERT INTO country_names(country_id, name) VALUES('fin', 'republic of finland');
INSERT INTO country_names(country_id, name) VALUES('fin', 'republiken finland');
INSERT INTO country_names(country_id, name) VALUES('fin', 'suomen tasavalta');
INSERT INTO country_names(country_id, name) VALUES('fin', 'suomi');
INSERT INTO country_names(country_id, name) VALUES('fji', 'fiji');
INSERT INTO country_names(country_id, name) VALUES('fji', 'fijian');
INSERT INTO country_names(country_id, name) VALUES('fji', 'republic of fiji');
INSERT INTO country_names(country_id, name) VALUES('fra', 'francais');
INSERT INTO country_names(country_id, name) VALUES('fra', 'francaise');
INSERT INTO country_names(country_id, name) VALUES('fra', 'france');
INSERT INTO country_names(country_id, name) VALUES('fra', 'french');
INSERT INTO country_names(country_id, name) VALUES('gbr', 'britain');
INSERT INTO country_names(country_id, name) VALUES('gbr', 'british');
INSERT INTO country_names(country_id, name) VALUES('gbr', 'great britain');
INSERT INTO country_names(country_id, name) VALUES('grc', 'elliniki dimokratia');
INSERT INTO country_names(country_id, name) VALUES('grc', 'greece');
INSERT INTO country_names(country_id, name) VALUES('grc', 'greek');
INSERT INTO country_names(country_id, name) VALUES('grc', 'hellenic republic');
INSERT INTO country_names(country_id, name) VALUES('gtm', 'guatemala');
INSERT INTO country_names(country_id, name) VALUES('gtm', 'guatemalan');
INSERT INTO country_names(country_id, name) VALUES('gtm', 'republic of guatemala');
INSERT INTO country_names(country_id, name) VALUES('gtm', 'republica de guatemala');
INSERT INTO country_names(country_id, name) VALUES('haw', 'hawaii');
INSERT INTO country_names(country_id, name) VALUES('haw', 'hawaiian');
INSERT INTO country_names(country_id, name) VALUES('hkg', 'hk');
INSERT INTO country_names(country_id, name) VALUES('hkg', 'hong kong');
INSERT INTO country_names(country_id, name) VALUES('hnd', 'honduras');
INSERT INTO country_names(country_id, name) VALUES('hnd', 'republic of honduras');
INSERT INTO country_names(country_id, name) VALUES('hnd', 'republica de honduras');
INSERT INTO country_names(country_id, name) VALUES('hti', 'ayiti');
INSERT INTO country_names(country_id, name) VALUES('hti', 'haiti');
INSERT INTO country_names(country_id, name) VALUES('hti', 'haitian');
INSERT INTO country_names(country_id, name) VALUES('hti', 'repiblik d ayiti');
INSERT INTO country_names(country_id, name) VALUES('hti', 'republic of haiti');
INSERT INTO country_names(country_id, name) VALUES('hun', 'hungarian');
INSERT INTO country_names(country_id, name) VALUES('hun', 'hungary');
INSERT INTO country_names(country_id, name) VALUES('hun', 'magyarorszag');
INSERT INTO country_names(country_id, name) VALUES('ind', 'india');
INSERT INTO country_names(country_id, name) VALUES('ind', 'indian');
INSERT INTO country_names(country_id, name) VALUES('ind', 'republic of india');
INSERT INTO country_names(country_id, name) VALUES('irl', 'eire');
INSERT INTO country_names(country_id, name) VALUES('irl', 'ireland');
INSERT INTO country_names(country_id, name) VALUES('irl', 'irish');
INSERT INTO country_names(country_id, name) VALUES('irl', 'republic of ireland');
INSERT INTO country_names(country_id, name) VALUES('irn', 'iran');
INSERT INTO country_names(country_id, name) VALUES('irn', 'irani');
INSERT INTO country_names(country_id, name) VALUES('irn', 'islamic republic of iran');
INSERT INTO country_names(country_id, name) VALUES('irn', 'republic of iran');
INSERT INTO country_names(country_id, name) VALUES('irq', 'iraq');
INSERT INTO country_names(country_id, name) VALUES('irq', 'iraqi');
INSERT INTO country_names(country_id, name) VALUES('irq', 'republic of iraq');
INSERT INTO country_names(country_id, name) VALUES('isl', 'iceland');
INSERT INTO country_names(country_id, name) VALUES('isl', 'icelandic');
INSERT INTO country_names(country_id, name) VALUES('isl', 'icelandish');
INSERT INTO country_names(country_id, name) VALUES('isl', 'island');
INSERT INTO country_names(country_id, name) VALUES('isr', 'israel');
INSERT INTO country_names(country_id, name) VALUES('isr', 'israeli');
INSERT INTO country_names(country_id, name) VALUES('isr', 'state of israel');
INSERT INTO country_names(country_id, name) VALUES('ita', 'italian');
INSERT INTO country_names(country_id, name) VALUES('ita', 'italy');
INSERT INTO country_names(country_id, name) VALUES('jam', 'jamaica');
INSERT INTO country_names(country_id, name) VALUES('jam', 'jamaican');
INSERT INTO country_names(country_id, name) VALUES('jam', 'jumieka');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'japan');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'japanese');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'nihon');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'nihon-koku');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'nippon');
INSERT INTO country_names(country_id, name) VALUES('jpn', 'nippon-koku');
INSERT INTO country_names(country_id, name) VALUES('khm', 'cambodia');
INSERT INTO country_names(country_id, name) VALUES('khm', 'cambodian');
INSERT INTO country_names(country_id, name) VALUES('khm', 'kingdom of cambodia');
INSERT INTO country_names(country_id, name) VALUES('kor', 'korea');
INSERT INTO country_names(country_id, name) VALUES('kor', 'korean');
INSERT INTO country_names(country_id, name) VALUES('kor', 'republic of korean');
INSERT INTO country_names(country_id, name) VALUES('kor', 's korea');
INSERT INTO country_names(country_id, name) VALUES('kor', 's. korea');
INSERT INTO country_names(country_id, name) VALUES('kor', 'south korea');
INSERT INTO country_names(country_id, name) VALUES('kwt', 'kuwait');
INSERT INTO country_names(country_id, name) VALUES('kwt', 'state of kuwait');
INSERT INTO country_names(country_id, name) VALUES('lbn', 'lebanese');
INSERT INTO country_names(country_id, name) VALUES('lbn', 'lebanon');
INSERT INTO country_names(country_id, name) VALUES('lbn', 'republic of lebanon');
INSERT INTO country_names(country_id, name) VALUES('lbr', 'liberia');
INSERT INTO country_names(country_id, name) VALUES('lbr', 'liberian');
INSERT INTO country_names(country_id, name) VALUES('lbr', 'republic of liberia');
INSERT INTO country_names(country_id, name) VALUES('lie', 'furstentum liechtenstein');
INSERT INTO country_names(country_id, name) VALUES('lie', 'liechtenstein');
INSERT INTO country_names(country_id, name) VALUES('lie', 'principality of liechtenstein');
INSERT INTO country_names(country_id, name) VALUES('ltu', 'lietuvos');
INSERT INTO country_names(country_id, name) VALUES('ltu', 'lietuvos respublika');
INSERT INTO country_names(country_id, name) VALUES('ltu', 'lithuania');
INSERT INTO country_names(country_id, name) VALUES('ltu', 'lithuanian');
INSERT INTO country_names(country_id, name) VALUES('ltu', 'republic of lithuania');
INSERT INTO country_names(country_id, name) VALUES('lux', 'grand duchy of luxembourg');
INSERT INTO country_names(country_id, name) VALUES('lux', 'letzeburg');
INSERT INTO country_names(country_id, name) VALUES('lux', 'luxembourg');
INSERT INTO country_names(country_id, name) VALUES('lva', 'latvejas');
INSERT INTO country_names(country_id, name) VALUES('lva', 'latvia');
INSERT INTO country_names(country_id, name) VALUES('lva', 'latvian');
INSERT INTO country_names(country_id, name) VALUES('lva', 'latvijas');
INSERT INTO country_names(country_id, name) VALUES('lva', 'republic of latvia');
INSERT INTO country_names(country_id, name) VALUES('mac', 'macao');
INSERT INTO country_names(country_id, name) VALUES('mac', 'macau');
INSERT INTO country_names(country_id, name) VALUES('mar', 'kingdom of morocco');
INSERT INTO country_names(country_id, name) VALUES('mar', 'moroccan');
INSERT INTO country_names(country_id, name) VALUES('mar', 'morocco');
INSERT INTO country_names(country_id, name) VALUES('mex', 'mexican');
INSERT INTO country_names(country_id, name) VALUES('mex', 'mexico');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'burma');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'burmese');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'myanmar');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'republic of myanmar');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'republic of the union of myanmar');
INSERT INTO country_names(country_id, name) VALUES('mmr', 'union of myanmar');
INSERT INTO country_names(country_id, name) VALUES('mng', 'mongolia');
INSERT INTO country_names(country_id, name) VALUES('mng', 'mongolian');
INSERT INTO country_names(country_id, name) VALUES('nfl', 'foundland');
INSERT INTO country_names(country_id, name) VALUES('nfl', 'new found land');
INSERT INTO country_names(country_id, name) VALUES('nfl', 'new foundland');
INSERT INTO country_names(country_id, name) VALUES('nfl', 'newfoundland');
INSERT INTO country_names(country_id, name) VALUES('nld', 'dutch');
INSERT INTO country_names(country_id, name) VALUES('nld', 'kingdom of the netherlands');
INSERT INTO country_names(country_id, name) VALUES('nld', 'netherland');
INSERT INTO country_names(country_id, name) VALUES('nld', 'netherlands');
INSERT INTO country_names(country_id, name) VALUES('nld', 'netherlands, the');
INSERT INTO country_names(country_id, name) VALUES('nld', 'the netherlands');
INSERT INTO country_names(country_id, name) VALUES('nor', 'kingdom of norway');
INSERT INTO country_names(country_id, name) VALUES('nor', 'kongeriket norge');
INSERT INTO country_names(country_id, name) VALUES('nor', 'noreg');
INSERT INTO country_names(country_id, name) VALUES('nor', 'norge');
INSERT INTO country_names(country_id, name) VALUES('nor', 'norway');
INSERT INTO country_names(country_id, name) VALUES('nor', 'norwegian');
INSERT INTO country_names(country_id, name) VALUES('npl', 'democratic republic of nepal');
INSERT INTO country_names(country_id, name) VALUES('npl', 'federal democratic republic of nepal');
INSERT INTO country_names(country_id, name) VALUES('npl', 'nepal');
INSERT INTO country_names(country_id, name) VALUES('npl', 'nepala');
INSERT INTO country_names(country_id, name) VALUES('npl', 'nepalese');
INSERT INTO country_names(country_id, name) VALUES('npl', 'republic of nepal');
INSERT INTO country_names(country_id, name) VALUES('nzl', 'aotearoa');
INSERT INTO country_names(country_id, name) VALUES('nzl', 'new zealand');
INSERT INTO country_names(country_id, name) VALUES('nzl', 'zealand');
INSERT INTO country_names(country_id, name) VALUES('pan', 'panama');
INSERT INTO country_names(country_id, name) VALUES('pan', 'panamanian');
INSERT INTO country_names(country_id, name) VALUES('pan', 'republic of panama');
INSERT INTO country_names(country_id, name) VALUES('pan', 'republica de panama');
INSERT INTO country_names(country_id, name) VALUES('per', 'peru');
INSERT INTO country_names(country_id, name) VALUES('per', 'peruvian');
INSERT INTO country_names(country_id, name) VALUES('per', 'republic of peru');
INSERT INTO country_names(country_id, name) VALUES('per', 'republica del peru');
INSERT INTO country_names(country_id, name) VALUES('phl', 'filipino');
INSERT INTO country_names(country_id, name) VALUES('phl', 'philippines');
INSERT INTO country_names(country_id, name) VALUES('phl', 'pilipinas');
INSERT INTO country_names(country_id, name) VALUES('phl', 'republic of the philippines');
INSERT INTO country_names(country_id, name) VALUES('phl', 'the philippines');
INSERT INTO country_names(country_id, name) VALUES('phl', 'the republic of the philippines');
INSERT INTO country_names(country_id, name) VALUES('pol', 'poland');
INSERT INTO country_names(country_id, name) VALUES('pol', 'polish');
INSERT INTO country_names(country_id, name) VALUES('pol', 'polska');
INSERT INTO country_names(country_id, name) VALUES('pol', 'republic of poland');
INSERT INTO country_names(country_id, name) VALUES('pol', 'rzeczpospolita polska');
INSERT INTO country_names(country_id, name) VALUES('prt', 'portugal');
INSERT INTO country_names(country_id, name) VALUES('prt', 'portuguesa');
INSERT INTO country_names(country_id, name) VALUES('prt', 'portuguese');
INSERT INTO country_names(country_id, name) VALUES('prt', 'portuguese republic');
INSERT INTO country_names(country_id, name) VALUES('prt', 'republica pertuesa');
INSERT INTO country_names(country_id, name) VALUES('prt', 'republica portuguesa');
INSERT INTO country_names(country_id, name) VALUES('pry', 'paraguai');
INSERT INTO country_names(country_id, name) VALUES('pry', 'paraguai tavakuaireta');
INSERT INTO country_names(country_id, name) VALUES('pry', 'paraguay');
INSERT INTO country_names(country_id, name) VALUES('pry', 'republic of paraguay');
INSERT INTO country_names(country_id, name) VALUES('pry', 'republica del paraguay');
INSERT INTO country_names(country_id, name) VALUES('rou', 'romania');
INSERT INTO country_names(country_id, name) VALUES('rou', 'romanian');
INSERT INTO country_names(country_id, name) VALUES('rus', 'russia');
INSERT INTO country_names(country_id, name) VALUES('rus', 'russian');
INSERT INTO country_names(country_id, name) VALUES('sau', 'kingdom of saudi arabia');
INSERT INTO country_names(country_id, name) VALUES('sau', 'saudi');
INSERT INTO country_names(country_id, name) VALUES('sau', 'saudi arabia');
INSERT INTO country_names(country_id, name) VALUES('sau', 'saudi arabian');
INSERT INTO country_names(country_id, name) VALUES('slv', 'el salvador');
INSERT INTO country_names(country_id, name) VALUES('slv', 'el salvadorean');
INSERT INTO country_names(country_id, name) VALUES('slv', 'republic of el salvador');
INSERT INTO country_names(country_id, name) VALUES('slv', 'republica de el salvador');
INSERT INTO country_names(country_id, name) VALUES('slv', 'salvadorean');
INSERT INTO country_names(country_id, name) VALUES('srb', 'republic of serbia');
INSERT INTO country_names(country_id, name) VALUES('srb', 'republika srbija');
INSERT INTO country_names(country_id, name) VALUES('srb', 'serbia');
INSERT INTO country_names(country_id, name) VALUES('srb', 'serbian');
INSERT INTO country_names(country_id, name) VALUES('srb', 'srbija');
INSERT INTO country_names(country_id, name) VALUES('sur', 'dutch guiana');
INSERT INTO country_names(country_id, name) VALUES('sur', 'guiana');
INSERT INTO country_names(country_id, name) VALUES('sur', 'republic of suriname');
INSERT INTO country_names(country_id, name) VALUES('sur', 'republiek suriname');
INSERT INTO country_names(country_id, name) VALUES('sur', 'suriname');
INSERT INTO country_names(country_id, name) VALUES('swe', 'kingdom of sweden');
INSERT INTO country_names(country_id, name) VALUES('swe', 'konungariket sverige');
INSERT INTO country_names(country_id, name) VALUES('swe', 'sweden');
INSERT INTO country_names(country_id, name) VALUES('swe', 'swedish');
INSERT INTO country_names(country_id, name) VALUES('syr', 'syria');
INSERT INTO country_names(country_id, name) VALUES('syr', 'syrian');
INSERT INTO country_names(country_id, name) VALUES('syr', 'syrian arab republic');
INSERT INTO country_names(country_id, name) VALUES('tha', 'kingdom of thailand');
INSERT INTO country_names(country_id, name) VALUES('tha', 'thai');
INSERT INTO country_names(country_id, name) VALUES('tha', 'thailand');
INSERT INTO country_names(country_id, name) VALUES('tur', 'republic of turkey');
INSERT INTO country_names(country_id, name) VALUES('tur', 'republic of turkiye');
INSERT INTO country_names(country_id, name) VALUES('tur', 'turkey');
INSERT INTO country_names(country_id, name) VALUES('tur', 'turkish');
INSERT INTO country_names(country_id, name) VALUES('tur', 'turkiye');
INSERT INTO country_names(country_id, name) VALUES('tur', 'turkiye cumhuriyeti');
INSERT INTO country_names(country_id, name) VALUES('uar', 'united arab republic');
INSERT INTO country_names(country_id, name) VALUES('ury', 'oriental republic of uruguay');
INSERT INTO country_names(country_id, name) VALUES('ury', 'republic of uruguay');
INSERT INTO country_names(country_id, name) VALUES('ury', 'republica oriental del uruguay');
INSERT INTO country_names(country_id, name) VALUES('ury', 'republica oriental do uruguai');
INSERT INTO country_names(country_id, name) VALUES('ury', 'uruguai');
INSERT INTO country_names(country_id, name) VALUES('ury', 'uruguay');
INSERT INTO country_names(country_id, name) VALUES('usa', 'united states');
INSERT INTO country_names(country_id, name) VALUES('usa', 'united states america');
INSERT INTO country_names(country_id, name) VALUES('usa', 'united states of america');
INSERT INTO country_names(country_id, name) VALUES('usa', 'us');
INSERT INTO country_names(country_id, name) VALUES('usa', 'usa');
INSERT INTO country_names(country_id, name) VALUES('ven', 'bolivarian republic of venezuela');
INSERT INTO country_names(country_id, name) VALUES('ven', 'republica bolivariana de venezuela');
INSERT INTO country_names(country_id, name) VALUES('ven', 'venezuela');
INSERT INTO country_names(country_id, name) VALUES('ven', 'venezuelan');
INSERT INTO country_names(country_id, name) VALUES('zaf', 's africa');
INSERT INTO country_names(country_id, name) VALUES('zaf', 's african');
INSERT INTO country_names(country_id, name) VALUES('zaf', 's. africa');
INSERT INTO country_names(country_id, name) VALUES('zaf', 's. african');
INSERT INTO country_names(country_id, name) VALUES('zaf', 'south africa');
INSERT INTO country_names(country_id, name) VALUES('zaf', 'south african');
