INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_abbasi', 'afg', 'abbasi', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_afghani', 'afg', 'afghani', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_habibi', 'afg', 'habibi', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_qiran', 'afg', 'qiran', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_rupee', 'afg', 'rupee', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_sanar', 'afg', 'sanar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('afg_tilla', 'afg', 'tilla', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('alb_frang ar', 'alb', 'frang ar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('alb_lek', 'alb', 'lek', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('arg_argentino', 'arg', 'argentino', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('arg_centavo', 'arg', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('arg_peso', 'arg', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aus_crown', 'aus', 'crown', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aus_florin', 'aus', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aus_penny', 'aus', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aus_shilling', 'aus', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aus_sovereign', 'aus', 'sovereign', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_dukat', 'aut', 'dukat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_florin', 'aut', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_kreuzer', 'aut', 'kreuzer', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_krone', 'aut', 'krone', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_schilling', 'aut', 'schilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('aut_vereinsthaler', 'aut', 'vereinsthaler', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bel_centime', 'bel', 'centime', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bel_franc', 'bel', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bgr_lev', 'bgr', 'lev', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bgr_stotinka', 'bgr', 'stotinka', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bmu_crown', 'bmu', 'crown', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_boliviano', 'bol', 'boliviano', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_centavo', 'bol', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_escudo', 'bol', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_melgarejo', 'bol', 'melgarejo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_onza', 'bol', 'onza', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bol_sol', 'bol', 'sol', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('bra_real', 'bra', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('can_cent', 'can', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('can_dollar', 'can', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('can_maple', 'can', 'maple', 'bullion');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('can_sovereign', 'can', 'sovereign', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('che_franc', 'che', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chl_centavo', 'chl', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chl_decimo', 'chl', 'decimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chl_peso', 'chl', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chn_cent', 'chn', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chn_chio', 'chn', 'chio', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chn_dollar', 'chn', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('chn_yuan', 'chn', 'yuan', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('col_centavo', 'col', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('col_decimo', 'col', 'decimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('col_peso', 'col', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('col_real', 'col', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('com_franc', 'com', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cri_centavo', 'cri', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cri_colon', 'cri', 'colon', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cri_escudo', 'cri', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cri_onza', 'cri', 'onza', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cri_peso', 'cri', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('csk_dukat', 'csk', 'dukat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('csk_koruna', 'csk', 'koruna', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cub_centavo', 'cub', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cub_peso', 'cub', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cuw_gulden', 'cuw', 'gulden', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('cyp_piastre', 'cyp', 'piastre', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('deu_mark', 'deu', 'mark', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('deu_pfennig', 'deu', 'pfennig', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES("dnk_christian d'or", 'dnk', "christian d'or", 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('dnk_krone', 'dnk', 'krone', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('dnk_ore', 'dnk', 'ore', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ecu_centavo', 'ecu', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ecu_condor', 'ecu', 'condor', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ecu_decimo', 'ecu', 'decimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ecu_sucre', 'ecu', 'sucre', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('egy_ghirsh', 'egy', 'ghirsh', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('egy_pound', 'egy', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eri_centisimo', 'eri', 'centisimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eri_lira', 'eri', 'lira', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eri_tallero', 'eri', 'tallero', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('esp_centimo', 'esp', 'centimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('esp_escudo', 'esp', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('esp_peseta', 'esp', 'peseta', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('esp_real', 'esp', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('est_kroon', 'est', 'kroon', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eth_birr', 'eth', 'birr', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eth_gersh', 'eth', 'gersh', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eth_santeem', 'eth', 'santeem', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('eth_wark', 'eth', 'wark', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fin_markka', 'fin', 'markka', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fin_pennia', 'fin', 'pennia', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fji_florin', 'fji', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fji_penny', 'fji', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fji_shilling', 'fji', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fra_centime', 'fra', 'centime', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('fra_franc', 'fra', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_britannia', 'gbr', 'britannia', 'bullion');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_crown', 'gbr', 'crown', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_dollar', 'gbr', 'trade dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_florin', 'gbr', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_penny', 'gbr', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_pound', 'gbr', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_shilling', 'gbr', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gbr_sovereign', 'gbr', 'sovereign', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('grc_drachma', 'grc', 'drachma', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('grc_lepton', 'grc', 'lepton', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gtm_centavo', 'gtm', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gtm_centimo', 'gtm', 'centimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gtm_peso', 'gtm', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gtm_quetzal', 'gtm', 'quetzal', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('gtm_real', 'gtm', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('haw_cent', 'haw', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('haw_dollar', 'haw', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hkg_cent', 'hkg', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hkg_dollar', 'hkg', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hnd_centavo', 'hnd', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hnd_lempira', 'hnd', 'lempira', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hnd_peso', 'hnd', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hti_centime', 'hti', 'centime', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hti_gourde', 'hti', 'gourde', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hun_dukat', 'hun', 'dukat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hun_forint', 'hun', 'forint', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hun_korona', 'hun', 'korona', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hun_krajczar', 'hun', 'krajczar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('hun_pengo', 'hun', 'pengo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ind_anna', 'ind', 'anna', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ind_mohur', 'ind', 'mohur', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ind_rupee', 'ind', 'rupee', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ind_sovereign', 'ind', 'sovereign', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irl_crown', 'irl', 'crown', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irl_florin', 'irl', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irl_shilling', 'irl', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_dinar', 'irn', 'dinar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_pahlavi', 'irn', 'pahlavi', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_qiran', 'irn', 'qiran', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_rial', 'irn', 'rial', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_shahi', 'irn', 'shahi', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irn_toman', 'irn', 'toman', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irq_fils', 'irq', 'fils', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('irq_riyal', 'irq', 'riyal', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('isl_krona', 'isl', 'krona', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('isr_pound', 'isr', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('isr_pruta', 'isr', 'pruta', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ita_centesimo', 'ita', 'centesimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ita_lira', 'ita', 'lira', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('jam_penny', 'jam', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('jpn_dollar', 'jpn', 'trade dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('jpn_sen', 'jpn', 'sen', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('jpn_yen', 'jpn', 'yen', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('khm_centime', 'khm', 'centime', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('khm_franc', 'khm', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('khm_piastre', 'khm', 'piastre', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('kor_chon', 'kor', 'chon', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('kor_whan', 'kor', 'whan', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('kor_won', 'kor', 'won', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('kor_yang', 'kor', 'yang', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('kwt_dinar', 'kwt', 'dinar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lbn_piastre', 'lbn', 'piastre', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lbr_cent', 'lbr', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lbr_dollar', 'lbr', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lie_frank', 'lie', 'frank', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lie_krone', 'lie', 'krone', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lie_thaler', 'lie', 'thaler', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ltu_litas', 'ltu', 'litas', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lux_franc', 'lux', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('lva_lats', 'lva', 'lats', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mac_pataca', 'mac', 'pataca', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mar_dirham', 'mar', 'dirham', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mar_franc', 'mar', 'franc', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mar_rial', 'mar', 'rial', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mex_centavo', 'mex', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mex_escudo', 'mex', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mex_peso', 'mex', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mex_real', 'mex', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mmr_anna', 'mmr', 'anna', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mmr_kyat', 'mmr', 'kyat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mmr_rupee', 'mmr', 'rupee', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mng_mongo', 'mng', 'mongo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('mng_tukhrik', 'mng', 'tukhrik', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nfl_cent', 'nfl', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nfl_dollar', 'nfl', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nld_cents', 'nld', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nld_dukaat', 'nld', 'dukaat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nld_gulden', 'nld', 'gulden', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nor_krone', 'nor', 'krone', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nor_ore', 'nor', 'ore', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nor_skilling', 'nor', 'skilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nor_speciedaler', 'nor', 'speciedaler', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('npl_paisa', 'npl', 'paisa', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('npl_rupee', 'npl', 'rupee', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nzl_crown', 'nzl', 'crown', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nzl_florin', 'nzl', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nzl_penny', 'nzl', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('nzl_shilling', 'nzl', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('pan_balboa', 'pan', 'balboa', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('pan_centesimo', 'pan', 'centesimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_dinero', 'per', 'dinero', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_escudo', 'per', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_libra', 'per', 'libra', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_peseta', 'per', 'peseta', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_real', 'per', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('per_sol', 'per', 'sol', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('phl_centavo', 'phl', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('phl_centimo', 'phl', 'centimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('phl_peso', 'phl', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('pol_zloty', 'pol', 'zloty', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('prt_centavo', 'prt', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('prt_escudo', 'prt', 'escudo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('prt_real', 'prt', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('pry_peso', 'pry', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('rou_banu', 'rou', 'banu', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('rou_leu', 'rou', 'leu', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('rus_kopek', 'rus', 'kopek', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('rus_ruble', 'rus', 'ruble', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('sau_guinea', 'sau', 'guinea', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('sau_riyal', 'sau', 'riyal', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('sau_sovereign', 'sau', 'sovereign', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('slv_centavo', 'slv', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('slv_colon', 'slv', 'colon', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('slv_peso', 'slv', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('srb_dinar', 'srb', 'dinar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('srb_para', 'srb', 'para', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('sur_gulden', 'sur', 'gulden', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('swe_carolin', 'swe', 'carolin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('swe_dukat', 'swe', 'dukat', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('swe_krona', 'swe', 'krona', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('swe_ore', 'swe', 'ore', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('swe_riksdaler riksmynt', 'swe', 'riksdaler riksmynt', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('syr_lira', 'syr', 'lira', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('syr_piastre', 'syr', 'piastre', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('syr_pound', 'syr', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tha_baht', 'tha', 'baht', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tha_salung', 'tha', 'salung', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tha_satang', 'tha', 'satang', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tur_kurus', 'tur', 'kurus', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tur_kurusmdl', 'tur', 'kurus (monnaies de luxe)', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tur_lira', 'tur', 'lira', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('tur_para', 'tur', 'para', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('uar_ghirsh', 'uar', 'ghirsh', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('uar_pound', 'uar', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ury_centesimo', 'ury', 'centesimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ury_peso', 'ury', 'peso', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('usa_bullion', 'usa', 'bullion', 'bullion');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('usa_cent', 'usa', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('usa_dollar', 'usa', 'dollar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ven_bolivar', 'ven', 'bolivar', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ven_centavo', 'ven', 'centavo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ven_centimo', 'ven', 'centimo', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ven_real', 'ven', 'real', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('ven_venezolano', 'ven', 'venezolano', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_cent', 'zaf', 'cent', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_florin', 'zaf', 'florin', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_krugerrand', 'zaf', 'krugerrand', 'bullion');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_penny', 'zaf', 'penny', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_pond', 'zaf', 'pond', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_pound', 'zaf', 'pound', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_rand', 'zaf', 'rand', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_shilling', 'zaf', 'shilling', 'none');
INSERT INTO denominations(denomination_id, country_id, display_name, tags) VALUES('zaf_sovereign', 'zaf', 'sovereign', 'none');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_abbasi', 'abbasi');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_abbasi', 'abbasis');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_afghani', 'afghani');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_afghani', 'afghanis');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_habibi', 'habibi');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_habibi', 'habibis');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_qiran', 'qiran');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_qiran', 'qirans');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_rupee', 'rupee');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_rupee', 'rupees');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_sanar', 'sanar');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_sanar', 'sanars');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_tilla', 'tilla');
INSERT INTO denomination_names(denomination_id, name) VALUES('afg_tilla', 'tillas');
INSERT INTO denomination_names(denomination_id, name) VALUES('alb_frang ar', 'frang ar');
INSERT INTO denomination_names(denomination_id, name) VALUES('alb_frang ar', 'franga ar');
INSERT INTO denomination_names(denomination_id, name) VALUES('alb_lek', 'lek');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_argentino', 'argentino');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_argentino', 'argentinos');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('arg_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_crown', 'crown');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_crown', 'crowns');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_shilling', 'shillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('aus_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_dukat', 'dukat');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_dukat', 'dukaten');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_kreuzer', 'kreuzer');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_krone', 'krone');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_krone', 'kronen');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_schilling', 'schilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_schilling', 'schillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('aut_vereinsthaler', 'vereinsthaler');
INSERT INTO denomination_names(denomination_id, name) VALUES('bel_centime', 'centime');
INSERT INTO denomination_names(denomination_id, name) VALUES('bel_centime', 'centimes');
INSERT INTO denomination_names(denomination_id, name) VALUES('bel_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('bel_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('bgr_lev', 'lev');
INSERT INTO denomination_names(denomination_id, name) VALUES('bgr_lev', 'leva');
INSERT INTO denomination_names(denomination_id, name) VALUES('bgr_stotinka', 'stotinka');
INSERT INTO denomination_names(denomination_id, name) VALUES('bgr_stotinka', 'stotinki');
INSERT INTO denomination_names(denomination_id, name) VALUES('bmu_crown', 'crown');
INSERT INTO denomination_names(denomination_id, name) VALUES('bmu_crown', 'crowns');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_boliviano', 'boliviano');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_boliviano', 'bolivianos');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_centavo', 'centecimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_centavo', 'centecimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_melgarejo', 'melgarejo');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_melgarejo', 'melgarejos');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_onza', 'onza');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_onza', 'onzas');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_sol', 'sol');
INSERT INTO denomination_names(denomination_id, name) VALUES('bol_sol', 'soles');
INSERT INTO denomination_names(denomination_id, name) VALUES('bra_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('bra_real', 'reis');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_maple', 'maple');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_maple', 'maples');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('can_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('che_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('che_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_decimo', 'decimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_decimo', 'decimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('chl_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_chio', 'chio');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('chn_yuan', 'yuan');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_decimo', 'decimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_decimo', 'decimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('col_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('com_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('com_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_colon', 'colon');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_colon', 'colones');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_onza', 'onza');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_onza', 'onzas');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('cri_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('csk_dukat', 'dukat');
INSERT INTO denomination_names(denomination_id, name) VALUES('csk_dukat', 'dukaty');
INSERT INTO denomination_names(denomination_id, name) VALUES('csk_dukat', 'dukatu');
INSERT INTO denomination_names(denomination_id, name) VALUES('csk_koruna', 'koruna');
INSERT INTO denomination_names(denomination_id, name) VALUES('csk_koruna', 'korun');
INSERT INTO denomination_names(denomination_id, name) VALUES('cub_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('cub_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('cub_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('cub_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('cuw_gulden', 'gulden');
INSERT INTO denomination_names(denomination_id, name) VALUES('cuw_gulden', 'guilder');
INSERT INTO denomination_names(denomination_id, name) VALUES('cuw_gulden', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('cyp_piastre', 'piastre');
INSERT INTO denomination_names(denomination_id, name) VALUES('cyp_piastre', 'piastres');
INSERT INTO denomination_names(denomination_id, name) VALUES('deu_mark', 'mark');
INSERT INTO denomination_names(denomination_id, name) VALUES('deu_mark', 'marks');
INSERT INTO denomination_names(denomination_id, name) VALUES('deu_pfennig', 'pfennig');
INSERT INTO denomination_names(denomination_id, name) VALUES('deu_pfennig', 'pfennigs');
INSERT INTO denomination_names(denomination_id, name) VALUES("dnk_christian d'or", "christian d'or");
INSERT INTO denomination_names(denomination_id, name) VALUES("dnk_christian d'or", 'christian');
INSERT INTO denomination_names(denomination_id, name) VALUES("dnk_christian d'or", "d'or");
INSERT INTO denomination_names(denomination_id, name) VALUES('dnk_krone', 'krone');
INSERT INTO denomination_names(denomination_id, name) VALUES('dnk_krone', 'kroner');
INSERT INTO denomination_names(denomination_id, name) VALUES('dnk_ore', 'ore');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_condor', 'condor');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_decimo', 'decimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_decimo', 'decimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_sucre', 'sucre');
INSERT INTO denomination_names(denomination_id, name) VALUES('ecu_sucre', 'sucres');
INSERT INTO denomination_names(denomination_id, name) VALUES('egy_ghirsh', 'ghirsh');
INSERT INTO denomination_names(denomination_id, name) VALUES('egy_ghirsh', 'qirsh');
INSERT INTO denomination_names(denomination_id, name) VALUES('egy_ghirsh', 'piastre');
INSERT INTO denomination_names(denomination_id, name) VALUES('egy_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('egy_pound', 'pounds');
INSERT INTO denomination_names(denomination_id, name) VALUES('eri_centisimo', 'centisimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('eri_centisimo', 'centesimi');
INSERT INTO denomination_names(denomination_id, name) VALUES('eri_lira', 'lira');
INSERT INTO denomination_names(denomination_id, name) VALUES('eri_lira', 'lire');
INSERT INTO denomination_names(denomination_id, name) VALUES('eri_tallero', 'tallero');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_centimo', 'centimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_centimo', 'centimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_peseta', 'peseta');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_peseta', 'pesetas');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('esp_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('est_kroon', 'kroon');
INSERT INTO denomination_names(denomination_id, name) VALUES('est_kroon', 'krooni');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_birr', 'birr');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_birr', 'birrs');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_gersh', 'gersh');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_santeem', 'santeem');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_wark', 'wark');
INSERT INTO denomination_names(denomination_id, name) VALUES('eth_wark', 'warks');
INSERT INTO denomination_names(denomination_id, name) VALUES('fin_markka', 'markka');
INSERT INTO denomination_names(denomination_id, name) VALUES('fin_markka', 'markaa');
INSERT INTO denomination_names(denomination_id, name) VALUES('fin_pennia', 'pennia');
INSERT INTO denomination_names(denomination_id, name) VALUES('fji_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('fji_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('fji_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('fji_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('fra_centime', 'centime');
INSERT INTO denomination_names(denomination_id, name) VALUES('fra_centime', 'centimes');
INSERT INTO denomination_names(denomination_id, name) VALUES('fra_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('fra_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_britannia', 'britannia');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_britannia', 'britannias');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_crown', 'crown');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_crown', 'crowns');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_dollar', 'trade dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_dollar', 'trade dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_pound', 'pounds');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_shilling', 'shillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('gbr_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_drachma', 'drachma');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_drachma', 'drachmai');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_drachma', 'drachmae');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_lepton', 'lepton');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_lepton', 'lepto');
INSERT INTO denomination_names(denomination_id, name) VALUES('grc_lepton', 'lepta');
INSERT INTO denomination_names(denomination_id, name) VALUES('haw_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('haw_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('haw_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('haw_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('hkg_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('hkg_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('hkg_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('hkg_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_lempira', 'lempira');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_lempira', 'lempiras');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('hnd_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('hti_centime', 'centime');
INSERT INTO denomination_names(denomination_id, name) VALUES('hti_centime', 'centimes');
INSERT INTO denomination_names(denomination_id, name) VALUES('hti_gourde', 'gourde');
INSERT INTO denomination_names(denomination_id, name) VALUES('hti_gourde', 'gourdes');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_dukat', 'dukat');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_dukat', 'ducat');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_dukat', 'dukats');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_dukat', 'ducats');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_forint', 'forint');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_korona', 'korona');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_krajczar', 'krajczar');
INSERT INTO denomination_names(denomination_id, name) VALUES('hun_pengo', 'pengo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_anna', 'anna');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_anna', 'annas');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_mohur', 'mohur');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_mohur', 'mohurs');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_rupee', 'rupee');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_rupee', 'rupees');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('ind_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_crown', 'crown');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_crown', 'crowns');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('irl_shilling', 'shillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('irq_fils', 'fils');
INSERT INTO denomination_names(denomination_id, name) VALUES('irq_riyal', 'riyal');
INSERT INTO denomination_names(denomination_id, name) VALUES('irq_riyal', 'riyals');
INSERT INTO denomination_names(denomination_id, name) VALUES('isl_krona', 'krona');
INSERT INTO denomination_names(denomination_id, name) VALUES('isl_krona', 'kronur');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_centesimo', 'centesimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_centesimo', 'centesimi');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_centesimo', 'centesimis');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_lira', 'lira');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_lira', 'lire');
INSERT INTO denomination_names(denomination_id, name) VALUES('ita_lira', 'liras');
INSERT INTO denomination_names(denomination_id, name) VALUES('jam_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('jam_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_dollar', 'trade dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_dollar', 'trade dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_sen', 'sen');
INSERT INTO denomination_names(denomination_id, name) VALUES('jpn_yen', 'yen');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_centime', 'centime');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_centime', 'centimes');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_piastre', 'piastre');
INSERT INTO denomination_names(denomination_id, name) VALUES('khm_piastre', 'piastres');
INSERT INTO denomination_names(denomination_id, name) VALUES('kor_chon', 'chon');
INSERT INTO denomination_names(denomination_id, name) VALUES('kor_whan', 'whan');
INSERT INTO denomination_names(denomination_id, name) VALUES('kor_won', 'won');
INSERT INTO denomination_names(denomination_id, name) VALUES('kor_yang', 'yang');
INSERT INTO denomination_names(denomination_id, name) VALUES('kwt_dinar', 'dinar');
INSERT INTO denomination_names(denomination_id, name) VALUES('kwt_dinar', 'dinars');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbn_piastre', 'piastre');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbn_piastre', 'piastres');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbr_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbr_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbr_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('lbr_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('ltu_litas', 'litas');
INSERT INTO denomination_names(denomination_id, name) VALUES('ltu_litas', 'litu');
INSERT INTO denomination_names(denomination_id, name) VALUES('ltu_litas', 'litai');
INSERT INTO denomination_names(denomination_id, name) VALUES('lux_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('lux_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('lux_franc', 'frang');
INSERT INTO denomination_names(denomination_id, name) VALUES('lux_franc', 'frangs');
INSERT INTO denomination_names(denomination_id, name) VALUES('lva_lats', 'lats');
INSERT INTO denomination_names(denomination_id, name) VALUES('lva_lats', 'lati');
INSERT INTO denomination_names(denomination_id, name) VALUES('mac_pataca', 'pataca');
INSERT INTO denomination_names(denomination_id, name) VALUES('mac_pataca', 'patacas');
INSERT INTO denomination_names(denomination_id, name) VALUES('mar_dirham', 'dirham');
INSERT INTO denomination_names(denomination_id, name) VALUES('mar_franc', 'franc');
INSERT INTO denomination_names(denomination_id, name) VALUES('mar_franc', 'francs');
INSERT INTO denomination_names(denomination_id, name) VALUES('mar_rial', 'rial');
INSERT INTO denomination_names(denomination_id, name) VALUES('mar_rial', 'rials');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('mex_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('mmr_anna', 'anna');
INSERT INTO denomination_names(denomination_id, name) VALUES('mmr_anna', 'annas');
INSERT INTO denomination_names(denomination_id, name) VALUES('mmr_kyat', 'kyat');
INSERT INTO denomination_names(denomination_id, name) VALUES('mmr_rupee', 'rupee');
INSERT INTO denomination_names(denomination_id, name) VALUES('mmr_rupee', 'rupees');
INSERT INTO denomination_names(denomination_id, name) VALUES('mng_mongo', 'mongo');
INSERT INTO denomination_names(denomination_id, name) VALUES('mng_tukhrik', 'tukhrik');
INSERT INTO denomination_names(denomination_id, name) VALUES('nld_cents', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('nld_cents', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('nld_dukaat', 'dukaat');
INSERT INTO denomination_names(denomination_id, name) VALUES('nld_gulden', 'gulden');
INSERT INTO denomination_names(denomination_id, name) VALUES('nld_gulden', 'guldens');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_krone', 'krone');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_krone', 'kroner');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_ore', 'ore');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_skilling', 'skilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_speciedaler', 'speciedaler');
INSERT INTO denomination_names(denomination_id, name) VALUES('nor_speciedaler', 'speciedalers');
INSERT INTO denomination_names(denomination_id, name) VALUES('npl_paisa', 'paisa');
INSERT INTO denomination_names(denomination_id, name) VALUES('npl_rupee', 'rupee');
INSERT INTO denomination_names(denomination_id, name) VALUES('npl_rupee', 'rupees');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_crown', 'crown');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_crown', 'crowns');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('nzl_shilling', 'shillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('pan_balboa', 'balboa');
INSERT INTO denomination_names(denomination_id, name) VALUES('pan_balboa', 'balboas');
INSERT INTO denomination_names(denomination_id, name) VALUES('pan_centesimo', 'centesimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('pan_centesimo', 'centesimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_dinero', 'dinero');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_dinero', 'dineros');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_libra', 'libra');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_libra', 'libras');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_peseta', 'peseta');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_peseta', 'pesetas');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_sol', 'sol');
INSERT INTO denomination_names(denomination_id, name) VALUES('per_sol', 'soles');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_centimo', 'centimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_centimo', 'centimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('phl_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('pol_zloty', 'zloty');
INSERT INTO denomination_names(denomination_id, name) VALUES('pol_zloty', 'zlote');
INSERT INTO denomination_names(denomination_id, name) VALUES('pol_zloty', 'zlotych');
INSERT INTO denomination_names(denomination_id, name) VALUES('pol_zloty', 'zlotego');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_escudo', 'escudo');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_escudo', 'escudos');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('prt_real', 'reis');
INSERT INTO denomination_names(denomination_id, name) VALUES('pry_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('pry_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('rou_banu', 'banu');
INSERT INTO denomination_names(denomination_id, name) VALUES('rou_banu', 'bani');
INSERT INTO denomination_names(denomination_id, name) VALUES('rou_leu', 'leu');
INSERT INTO denomination_names(denomination_id, name) VALUES('rou_leu', 'lei');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_kopek', 'kopek');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_kopek', 'kopeks');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_kopek', 'kopeck');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_kopek', 'kopecks');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_ruble', 'ruble');
INSERT INTO denomination_names(denomination_id, name) VALUES('rus_ruble', 'rubles');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_guinea', 'guinea');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_guinea', 'guineas');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_riyal', 'riyal');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_riyal', 'riyals');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('sau_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_colon', 'colon');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_colon', 'colones');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('slv_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('srb_dinar', 'dinar');
INSERT INTO denomination_names(denomination_id, name) VALUES('srb_dinar', 'dinara');
INSERT INTO denomination_names(denomination_id, name) VALUES('srb_para', 'para');
INSERT INTO denomination_names(denomination_id, name) VALUES('srb_para', 'pare');
INSERT INTO denomination_names(denomination_id, name) VALUES('sur_gulden', 'gulden');
INSERT INTO denomination_names(denomination_id, name) VALUES('sur_gulden', 'guldens');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_carolin', 'carolin');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_carolin', 'carolins');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_dukat', 'dukat');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_krona', 'krona');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_krona', 'kronor');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_ore', 'ore');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_ore', 'oren');
INSERT INTO denomination_names(denomination_id, name) VALUES('swe_riksdaler riksmynt', 'riksdaler riksmynt');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_lira', 'lira');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_lira', 'lire');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_piastre', 'piastre');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_piastre', 'piastres');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('syr_pound', 'pounds');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_bullion', 'bullion');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_bullion', 'bullions');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('usa_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_bolivar', 'bolivar');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_bolivar', 'bolivares');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_centimo', 'centimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_centimo', 'centimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_venezolano', 'venezolano');
INSERT INTO denomination_names(denomination_id, name) VALUES('ven_venezolano', 'venezolanos');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_florin', 'florin');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_florin', 'florins');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_krugerrand', 'krugerrand');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_krugerrand', 'krugerrands');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_penny', 'penny');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_penny', 'pence');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_pond', 'pond');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_pond', 'ponds');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_pound', 'pounds');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_rand', 'rand');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_shilling', 'shilling');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_shilling', 'shillings');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_sovereign', 'sovereign');
INSERT INTO denomination_names(denomination_id, name) VALUES('zaf_sovereign', 'sovereigns');
INSERT INTO denomination_names(denomination_id, name) VALUES('ury_centesimo', 'centesimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('ury_centesimo', 'centesimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('ury_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('ury_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_real', 'real');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_real', 'reales');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_peso', 'peso');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_peso', 'pesos');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_centimo', 'centimo');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_centimo', 'centimos');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_centavo', 'centavo');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_centavo', 'centavos');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_quetzal', 'quetzal');
INSERT INTO denomination_names(denomination_id, name) VALUES('gtm_quetzal', 'quetzales');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_shahi', 'shahi');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_shahi', 'shahis');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_qiran', 'qiran');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_qiran', 'qirans');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_dinar', 'dinar');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_dinar', 'dinars');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_toman', 'toman');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_toman', 'tomans');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_rial', 'rial');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_rial', 'rials');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_pahlavi', 'pahlavi');
INSERT INTO denomination_names(denomination_id, name) VALUES('irn_pahlavi', 'pahlavis');
INSERT INTO denomination_names(denomination_id, name) VALUES('isr_pruta', 'pruta');
INSERT INTO denomination_names(denomination_id, name) VALUES('isr_pruta', 'prutas');
INSERT INTO denomination_names(denomination_id, name) VALUES('isr_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('isr_pound', 'pounds');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_thaler', 'thaler');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_thaler', 'thalers');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_krone', 'krone');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_krone', 'kronen');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_frank', 'frank');
INSERT INTO denomination_names(denomination_id, name) VALUES('lie_frank', 'franken');
INSERT INTO denomination_names(denomination_id, name) VALUES('tha_salung', 'salung');
INSERT INTO denomination_names(denomination_id, name) VALUES('tha_baht', 'baht');
INSERT INTO denomination_names(denomination_id, name) VALUES('tha_satang', 'satang');
INSERT INTO denomination_names(denomination_id, name) VALUES('nfl_cent', 'cent');
INSERT INTO denomination_names(denomination_id, name) VALUES('nfl_cent', 'cents');
INSERT INTO denomination_names(denomination_id, name) VALUES('nfl_dollar', 'dollar');
INSERT INTO denomination_names(denomination_id, name) VALUES('nfl_dollar', 'dollars');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_para', 'para');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_para', 'paras');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_kurus', 'kurus');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_kurus', 'kurush');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_lira', 'lira');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_lira', 'liras');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_kurusmdl', 'kurus (monnaies de luxe)');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_kurusmdl', 'kurus');
INSERT INTO denomination_names(denomination_id, name) VALUES('tur_kurusmdl', 'kurush');
INSERT INTO denomination_names(denomination_id, name) VALUES('uar_ghirsh', 'ghirsh');
INSERT INTO denomination_names(denomination_id, name) VALUES('uar_pound', 'pound');
INSERT INTO denomination_names(denomination_id, name) VALUES('uar_pound', 'pounds');
